### ISSUE TITLE
Improve getTreeDisplay in TreePrinter.java

### ISSUE THREAD

**Issue by AdamJonsson** [KTH-DD2480-Group-2/Algorithms#3]
### Description
This function is used to display different tree structures. It has a high CC as its needs to print different characters at specific locations. However, the function should be refactored to a simpler structure to minimize the CC and cognitive load. There exist also room for optimization of the creation of the tree as a string. Therefore, the current CC does not necessarily need to be as high as it currently is.
### Data from Lizard tool:
* Path to function: `./src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java`
* Lines of code (NLOC): **82**
* Cyclomatic complexity (CCN): **27**
### Data JaCoCo:
* Branch coverage: **0%**

**Comment by AdamJonsson** [comment]
## Manually counting CC:
* PI (Number of decisions) = 26
* S (Number of exist points) = 1
* CC = PI - S + 2 = 26 - 1 + 2 = **27**

See comments with "PI" and "Exit points" for how they were calculated
```java
  // Print a binary tree.
  public static String getTreeDisplay(PrintableNode root) {

    StringBuilder sb = new StringBuilder();
    List<List<String>> lines = new ArrayList<List<String>>();
    List<PrintableNode> level = new ArrayList<PrintableNode>();
    List<PrintableNode> next = new ArrayList<PrintableNode>();

    level.add(root);
    int nn = 1;
    int widest = 0;

    while (nn != 0) { // PI = 1
      nn = 0;
      List<String> line = new ArrayList<String>();
      for (PrintableNode n : level) { // PI = 2
        if (n == null) { // PI = 3
          line.add(null);
          next.add(null);
          next.add(null);
        } else {
          String aa = n.getText();
          line.add(aa);
          if (aa.length() > widest) widest = aa.length(); // PI = 4

          next.add(n.getLeft());
          next.add(n.getRight());

          if (n.getLeft() != null) nn++; // PI = 5
          if (n.getRight() != null) nn++; // PI = 6
        }
      }

      if (widest % 2 == 1) widest++; // PI = 7

      lines.add(line);

      List<PrintableNode> tmp = level;
      level = next;
      next = tmp;
      next.clear();
    }

    int perpiece = lines.get(lines.size() - 1).size() * (widest + 4);
    for (int i = 0; i < lines.size(); i++) { // PI = 8
      List<String> line = lines.get(i);
      int hpw = (int) Math.floor(perpiece / 2f) - 1;
      if (i > 0) { // PI = 9
        for (int j = 0; j < line.size(); j++) { // PI = 10

          // split node
          char c = ' ';
          if (j % 2 == 1) { // PI = 11
            if (line.get(j - 1) != null) { // PI = 12
              c = (line.get(j) != null) ? '#' : '#'; // PI = 13
            } else {
              if (j < line.size() && line.get(j) != null) c = '#'; // PI = 14, PI = 15
            }
          }
          sb.append(c);

          // lines and spaces
          if (line.get(j) == null) { // PI = 16
            for (int k = 0; k < perpiece - 1; k++) { // PI = 17
              sb.append(' ');
            }
          } else {
            for (int k = 0; k < hpw; k++) { // PI = 18
              sb.append(j % 2 == 0 ? " " : "#"); // PI = 19
            }
            sb.append(j % 2 == 0 ? "#" : "#"); // PI = 20
            for (int k = 0; k < hpw; k++) { // PI = 21
              sb.append(j % 2 == 0 ? "#" : " "); // PI = 22
            }
          }
        }
        sb.append('\n');
      }
      for (int j = 0; j < line.size(); j++) { // PI = 23
        String f = line.get(j);
        if (f == null) f = ""; // PI = 24
        int gap1 = (int) Math.ceil(perpiece / 2f - f.length() / 2f);
        int gap2 = (int) Math.floor(perpiece / 2f - f.length() / 2f);

        for (int k = 0; k < gap1; k++) { // PI = 25
          sb.append(' ');
        }
        sb.append(f);
        for (int k = 0; k < gap2; k++) { // PI = 26
          sb.append(' ');
        }
      }
      sb.append('\n');

      perpiece /= 2;
    }
    return sb.toString(); // Exit points = 1
  }
```

**Comment by manjikian** [comment]
### Cyclomatic complexity calculation:

#### Cyclometric complexity = 26 - 1 + 2 = 27

---

- Number of decisions: 26
  - Line [34](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L34): while
  - Line [37](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L37): for
  - Line [38](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L38): if
  - Line [45](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L45): if
  - Line [50](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L50): if
  - Line [51](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L51): while
  - Line [55](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L55): if
  - Line [66](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L66): for
  - Line [69](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L69): if
  - Line [70](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L70): for
  - Line [74](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L74): if
  - Line [75](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L75): if
  - Line [76](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L76): ternary
  - Line [78](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L78): if, &&
  - Line [84](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L84): if
  - Line [85](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L85): for
  - Line [89](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L89): for
  - Line [90](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L90): ternary
  - Line [92](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L92): ternary
  - Line [93](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L93): for
  - Line [94](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L94): ternary
  - Line [100](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L100): for
  - Line [102](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L102): if
  - Line [106](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L106): for
  - Line [110](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java#L110): for
- number of exit points: 1
