### ISSUE TITLE
Improve knn() in QuadTree.java

### ISSUE THREAD

**Issue by manjikian** [KTH-DD2480-Group-2/Algorithms#4]
## Description
The function will find the _k_ nearest points in a Cartesian plane to a point specified by its two coordinates _x_ and _y_. The function is complex for two reasons. First, because the algorithm is hard coded for the 4 quadrants of the Cartesian plain. Second, because of repetition which duplicates the cyclomatic complexity.

## Refactoring
The obvious and easy refactoring step in this case is to eliminate the code duplication. Especially, that this part of code has an obvious purpose, which is finding closer points when we already found _k_ candidate points. The other step would be to rewrite the algorithm so that it is not hard-coded to 4 regions, but instead have an iterative algorithm that will iterate over all the regions.

The first refactoring was done and the result was reducing the cyclomatic complexity form 97 to 43.

---

- [x] CC count
- [x] DIY test
- [x] Write four tests
- [x] Refactor

### Data from Lizard tool:
* Path to function: `./src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java`
* Lines of code (NLOC): **113**
* Cyclomatic complexity (CCN): **91**
### Data JaCoCo:
* Branch coverage: **0%**

**Comment by manjikian** [comment]
### Cyclomatic complexity calculation:

#### Cyclometric complexity = 90 - 1 + 2 = 91

---

- Number of decisions: 90
  - Line [168](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L168): for
  - Line [172](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L172): ternary
  - Line [178](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L178): if
  - Line [180](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L180): if
  - Line [190](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L190): if, &&
  - Line [193](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L193): if, &&
  - Line [196](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L196): if, &&
  - Line [199](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L199): if, &&
  - Line [204](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L204): if
  - Line [210](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L210): ternary
  - Line [223](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L223): &&
  - Line [226](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L226): if
  - Line [228](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L228): if
  - Line [229](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L229): if
  - Line [230](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L230): if, if
  - Line [231](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L231): if, if
  - Line [232](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L232): if, if
  - Line [234](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L234): if, if
  - Line [235](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L235): if, if
  - Line [236](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L236): if, if
  - Line [239](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L239): if
  - Line [240](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L240): if, if
  - Line [241](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L241): if, if
  - Line [242](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L242): if, if
  - Line [244](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L244): if, if
  - Line [245](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L245): if, if
  - Line [246](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L246): if, if
  - Line [256](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L256): for
  - Line [258](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L258): if
  - Line [259](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L259): ternary
  - Line [262](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L262): &&
  - Line [265](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L265): if
  - Line [266](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L266): if
  - Line [267](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L267): if
  - Line [268](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L268): if
  - Line [269](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L269): if
  - Line [270](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L270): if
  - Line [272](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L272): if
  - Line [273](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L273): if
  - Line [274](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L274): if
  - Line [277](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L277): if
  - Line [278](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L278): if
  - Line [279](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L279): if
  - Line [280](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L280): if
  - Line [282](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L282): if
  - Line [283](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L283): if
  - Line [284](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L284): if
  - Line [291](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L291): if
  - Line [292](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L292): if
  - Line [293](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L293): if, if
  - Line [294](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L294): if, if
  - Line [295](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L295): if, if
  - Line [297](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L297): if, if
  - Line [298](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L298): if, if
  - Line [299](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L299): if, if
  - Line [302](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L302): if
  - Line [303](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L303): if, if
  - Line [304](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L304): if, if
  - Line [305](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L305): if, if
  - Line [307](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L307): if, if
  - Line [308](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L308): if, if
  - Line [309](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/42a91a94bcd213ffdd13651688b86522717b5f71/src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java#L309): if, if
- number of exit points: 1

**Comment by Autonymic** [comment]
**Cyclomatic complexity = PI - S + 2 = 88 - 1 + 2 = 89**

```
private void knn(int k, long x, long y, PriorityQueue<SortedPt> heap) {

      for (int i = 0; i < ptCount; i++) {						//PI = 1
        long xx = X[i], yy = Y[i];

        // Get largest radius.
        double radius = heap.isEmpty() ? POSITIVE_INFINITY : heap.peek().dist;		//PI = 2

        // Get distance from point to this point.
        double distance = Math.sqrt((xx - x) * (xx - x) + (yy - y) * (yy - y));

        // Add node to heap.
        if (heap.size() < k) {								//PI = 3
          heap.add(new SortedPt(distance, new Pt(xx, yy)));
        } else if (distance < radius) {							//PI = 4
          heap.poll();
          // System.out.println("POLLED: " + heap.poll());
          heap.add(new SortedPt(distance, new Pt(xx, yy)));
        }
      }

      int pointQuadrant = 0;

      // Dig to find the quadrant (x, y) belongs to.
      if (nw != null && region.contains(x, y)) {					//PI = 6
        nw.knn(k, x, y, heap);
        pointQuadrant = NORTH_WEST;
      } else if (ne != null && region.contains(x, y)) {					//PI = 8
        ne.knn(k, x, y, heap);
        pointQuadrant = NORTH_EAST;
      } else if (sw != null && region.contains(x, y)) {					//PI = 10
        sw.knn(k, x, y, heap);
        pointQuadrant = SOUTH_WEST;
      } else if (se != null && region.contains(x, y)) { // Use else clause?		//PI = 12
        se.knn(k, x, y, heap);
        pointQuadrant = SOUTH_EAST;
      }

      if (pointQuadrant == 0) {								//PI = 13
        // System.out.println("UNDEFINED QUADRANT?");
        // return;
      }

      // Get largest radius.
      double radius = heap.isEmpty() ? POSITIVE_INFINITY : heap.peek().dist;		//PI = 14

      // Find the center of this region at (cx, cy)
      long cx = (region.x1 + region.x2) / 2;
      long cy = (region.y1 + region.y2) / 2;

      // Compute the horizontal (dx) and vertical (dy) distance from the
      // point (x, y) to the nearest cell.
      long dx = Math.abs(x - cx);
      long dy = Math.abs(y - cy);

      boolean checkHorizontalCell = radius >= dx;
      boolean checkVerticalCell = radius >= dy;
      boolean checkDiagonalCell = checkHorizontalCell && checkVerticalCell;

      // TODO(williamfiset): Refactor.
      if (heap.size() == k) {								//PI = 15

        if (isNorth(pointQuadrant)) {							//PI = 16
          if (pointQuadrant == NORTH_WEST) {						//PI = 17
            if (checkHorizontalCell) if (ne != null) ne.knn(k, x, y, heap);		//PI = 19
            if (checkVerticalCell) if (sw != null) sw.knn(k, x, y, heap);		//PI = 21
            if (checkDiagonalCell) if (se != null) se.knn(k, x, y, heap);		//PI = 23
          } else {
            if (checkHorizontalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 25
            if (checkVerticalCell) if (se != null) se.knn(k, x, y, heap);		//PI = 27
            if (checkDiagonalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 29
          }
        } else {
          if (pointQuadrant == SOUTH_WEST) {						//PI = 30
            if (checkHorizontalCell) if (se != null) se.knn(k, x, y, heap);		//PI = 32
            if (checkVerticalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 34
            if (checkDiagonalCell) if (ne != null) ne.knn(k, x, y, heap);		//PI = 36
          } else {
            if (checkHorizontalCell) if (sw != null) sw.knn(k, x, y, heap);		//PI = 38
            if (checkVerticalCell) if (ne != null) ne.knn(k, x, y, heap);		//PI = 40
            if (checkDiagonalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 42
          }
        }

        // Still need to find k - heap.size() nodes!
      } else {

        // explore all quadrants ?
        // Do it lazy? Inspect return val after each call?

        for (int quadrant = 1; quadrant <= 4; quadrant++) {				//PI = 43

          if (quadrant == pointQuadrant) continue;					//PI = 44
          radius = heap.isEmpty() ? POSITIVE_INFINITY : heap.peek().dist;		//PI = 45
          checkHorizontalCell = radius >= dx;
          checkVerticalCell = radius >= dy;
          checkDiagonalCell = checkHorizontalCell && checkVerticalCell;

          // No validation
          if (heap.size() != k) {							//PI = 46
            if (isNorth(pointQuadrant)) {						//PI = 47
              if (pointQuadrant == NORTH_WEST) {					//PI = 48,
                if (ne != null) ne.knn(k, x, y, heap);					//PI = 49
                if (sw != null) sw.knn(k, x, y, heap);					//PI = 50
                if (se != null) se.knn(k, x, y, heap);					//PI = 51
              } else {
                if (nw != null) nw.knn(k, x, y, heap);					//PI = 52
                if (se != null) se.knn(k, x, y, heap);					//PI = 53
                if (nw != null) nw.knn(k, x, y, heap);					//PI = 54
              }
            } else {
              if (pointQuadrant == SOUTH_WEST) {					//PI = 55
                if (se != null) se.knn(k, x, y, heap);					//PI = 56
                if (nw != null) nw.knn(k, x, y, heap);					//PI = 57
                if (ne != null) ne.knn(k, x, y, heap);					//PI = 58
              } else {
                if (sw != null) sw.knn(k, x, y, heap);					//PI = 59
                if (ne != null) ne.knn(k, x, y, heap);					//PI = 60
                if (nw != null) nw.knn(k, x, y, heap);					//PI = 61
              }
            }

            // must intersect
          } else {

            if (isNorth(pointQuadrant)) {						//PI = 62
              if (pointQuadrant == NORTH_WEST) {					//PI = 63
                if (checkHorizontalCell) if (ne != null) ne.knn(k, x, y, heap);		//PI = 65
                if (checkVerticalCell) if (sw != null) sw.knn(k, x, y, heap);		//PI = 67
                if (checkDiagonalCell) if (se != null) se.knn(k, x, y, heap);		//PI = 69
              } else {
                if (checkHorizontalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 71
                if (checkVerticalCell) if (se != null) se.knn(k, x, y, heap);		//PI = 73
                if (checkDiagonalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 75
              }
            } else {
              if (pointQuadrant == SOUTH_WEST) {					//PI = 76
                if (checkHorizontalCell) if (se != null) se.knn(k, x, y, heap);		//PI = 78
                if (checkVerticalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 80
                if (checkDiagonalCell) if (ne != null) ne.knn(k, x, y, heap);		//PI = 82
              } else {
                if (checkHorizontalCell) if (sw != null) sw.knn(k, x, y, heap);		//PI = 84
                if (checkVerticalCell) if (ne != null) ne.knn(k, x, y, heap);		//PI = 86
                if (checkDiagonalCell) if (nw != null) nw.knn(k, x, y, heap);		//PI = 88
              }
            }
          }
        } // for
      } // if
    } // method
											//PI = 88, S = 1
  } // node
```
