### ISSUE TITLE
Improve GenericSegmentTree() in GenericSegmentTree.java

### ISSUE THREAD

**Issue by Autonymic** [KTH-DD2480-Group-2/Algorithms#9]
- [ ] Refactor
- [x] Write four tests
- [x] CC count

### Data from Lizard tool:
* Path to function: `./src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java`
* Lines of code (NLOC): **83**
* Cyclomatic complexity (CCN): **24**
### Data JaCoCo:
* Branch coverage: **54%**

**Comment by Autonymic** [comment]
### Manual counting of CC

PI (Number of decisions) = 22
S (Number of exit points) = 4
CC = PI - S + 2 = 22 - 4 + 2 = 20 **does not equal the Lizard result**

See comments with "PI" and "S" for how they were calculated

```
public GenericSegmentTree(
      long[] values,
      SegmentCombinationFn segmentCombinationFunction,
      RangeUpdateFn rangeUpdateFunction) {
    if (values == null) {										//PI = 1, SI = 1
      throw new IllegalArgumentException("Segment tree values cannot be null.");
    }
    if (segmentCombinationFunction == null) {								//PI = 2, SI = 2
      throw new IllegalArgumentException("Please specify a valid segment combination function.");
    }
    if (rangeUpdateFunction == null) {									//PI = 3, SI = 3
      throw new IllegalArgumentException("Please specify a valid range update function.");
    }
    n = values.length;

    // The size of the segment tree `t`
    //
    // TODO(william): Investigate to reduce this space. There are only 2n-1 segments, so we should
    // be able to reduce the space, but may need to reorganize the tree/queries. One idea is to use
    // the Eulerian tour structure of the tree to densely pack the segments.
    int N = 4 * n;

    t = new Long[N];
    lazy = new Long[N];

    // Select the specified combination function
    if (segmentCombinationFunction == SegmentCombinationFn.SUM) {
      combinationFn = sumCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {						//PI = 4, SI = 3
        ruf = sumQuerySumUpdate;
        lruf = lsumQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {						//PI = 5, SI = 3
        ruf = sumQueryAssignUpdate;
        lruf = lsumQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {					//PI = 6, SI = 3
        ruf = sumQueryMulUpdate;
        lruf = lsumQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.MIN) {				//PI = 7, SI = 3
      combinationFn = minCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {						//PI = 8, SI = 3
        ruf = minQuerySumUpdate;
        lruf = lminQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {						//PI = 9, SI = 3
        ruf = minQueryAssignUpdate;
        lruf = lminQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {					//PI = 10, SI = 3
        ruf = minQueryMulUpdate;
        lruf = lminQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.MAX) {				//PI = 11, SI = 3
      combinationFn = maxCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {						//PI = 12, SI = 3
        ruf = maxQuerySumUpdate;
        lruf = lmaxQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {						//PI = 13, SI = 3
        ruf = maxQueryAssignUpdate;
        lruf = lmaxQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {					//PI = 14, SI = 3
        ruf = maxQueryMulUpdate;
        lruf = lmaxQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.GCD) {				//PI = 15, SI = 3
      combinationFn = gcdCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {						//PI = 16, SI = 3
        ruf = gcdQuerySumUpdate;
        lruf = lgcdQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {						//PI = 17, SI = 3
        ruf = gcdQueryAssignUpdate;
        lruf = lgcdQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {					//PI = 18, SI = 3
        ruf = gcdQueryMulUpdate;
        lruf = lgcdQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.PRODUCT) {				//PI = 19, SI = 3
      combinationFn = productCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {						//PI = 20, SI = 3
        ruf = productQuerySumUpdate;
        lruf = lproductQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {						//PI = 21, SI = 3
        ruf = productQueryAssignUpdate;
        lruf = lproductQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {					//PI = 22, SI = 3
        ruf = productQueryMulUpdate;
        lruf = lproductQueryMulUpdate;
      }
    } else {
      throw new UnsupportedOperationException(
          "Combination function not supported: " + segmentCombinationFunction);
    }

    buildSegmentTree(0, 0, n - 1, values);
  }
```

**Comment by manjikian** [comment]
### Cyclomatic complexity calculation:

#### Cyclometric complexity = 23 - 1 + 2 = 24

---

- Number of decisions: 23
  - Line [169](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L169): if
  - Line [172](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L172): if
  - Line [175](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L175): if
  - Line [191](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L191): if
  - Line [193](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L193): if
  - Line [196](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L196): if
  - Line [199](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L199): if
  - Line [203](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L203): if
  - Line [205](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L205): if
  - Line [208](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L208): if
  - Line [211](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L211): if
  - Line [215](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L215): if
  - Line [217](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L217): if
  - Line [220](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L220): if
  - Line [223](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L223): if
  - Line [227](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L227): if
  - Line [229](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L229): if
  - Line [232](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L232): if
  - Line [235](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L235): if
  - Line [239](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L239): if
  - Line [241](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L241): if
  - Line [244](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L244): if
  - Line [247](https://github.com/KTH-DD2480-Group-2/Algorithms/blob/a3761a55453db58d52795f96c05c4d56df39b465/src/main/java/com/williamfiset/algorithms/datastructures/segmenttree/GenericSegmentTree.java#L247): if
- number of exit points: 1

**Comment by Autonymic** [comment]
**For the refactoring plan, see comments.**
```java
public GenericSegmentTree(
      long[] values,
      SegmentCombinationFn segmentCombinationFunction,
      RangeUpdateFn rangeUpdateFunction) {
    if (values == null) {
      throw new IllegalArgumentException("Segment tree values cannot be null.");
    }
    if (segmentCombinationFunction == null) {
      throw new IllegalArgumentException("Please specify a valid segment combination function.");
    }
    if (rangeUpdateFunction == null) {
      throw new IllegalArgumentException("Please specify a valid range update function.");
    }
    n = values.length;

    // The size of the segment tree `t`
    //
    // TODO(william): Investigate to reduce this space. There are only 2n-1 segments, so we should
    // be able to reduce the space, but may need to reorganize the tree/queries. One idea is to use
    // the Eulerian tour structure of the tree to densely pack the segments.
    int N = 4 * n;

    t = new Long[N];
    lazy = new Long[N];

    // Refactor plan: Move to other function. These if statements check for all combinations of combination functions
    // and update functions and sets certain values differently depending on which combination. These actions could be
    // refactored into a separate method in this class.

    // Select the specified combination function
    if (segmentCombinationFunction == SegmentCombinationFn.SUM) {
      combinationFn = sumCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {
        ruf = sumQuerySumUpdate;
        lruf = lsumQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {
        ruf = sumQueryAssignUpdate;
        lruf = lsumQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {
        ruf = sumQueryMulUpdate;
        lruf = lsumQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.MIN) {
      combinationFn = minCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {
        ruf = minQuerySumUpdate;
        lruf = lminQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {
        ruf = minQueryAssignUpdate;
        lruf = lminQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {
        ruf = minQueryMulUpdate;
        lruf = lminQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.MAX) {
      combinationFn = maxCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {
        ruf = maxQuerySumUpdate;
        lruf = lmaxQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {
        ruf = maxQueryAssignUpdate;
        lruf = lmaxQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {
        ruf = maxQueryMulUpdate;
        lruf = lmaxQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.GCD) {
      combinationFn = gcdCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {
        ruf = gcdQuerySumUpdate;
        lruf = lgcdQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {
        ruf = gcdQueryAssignUpdate;
        lruf = lgcdQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {
        ruf = gcdQueryMulUpdate;
        lruf = lgcdQueryMulUpdate;
      }
    } else if (segmentCombinationFunction == SegmentCombinationFn.PRODUCT) {
      combinationFn = productCombinationFn;
      if (rangeUpdateFunction == RangeUpdateFn.ADDITION) {
        ruf = productQuerySumUpdate;
        lruf = lproductQuerySumUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.ASSIGN) {
        ruf = productQueryAssignUpdate;
        lruf = lproductQueryAssignUpdate;
      } else if (rangeUpdateFunction == RangeUpdateFn.MULTIPLICATION) {
        ruf = productQueryMulUpdate;
        lruf = lproductQueryMulUpdate;
      }
    } else {
      throw new UnsupportedOperationException(
          "Combination function not supported: " + segmentCombinationFunction);
    }

    buildSegmentTree(0, 0, n - 1, values);
  }
```
